
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListarService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8081/listar?wsdl")
public class ListarService
    extends Service
{

    private final static URL LISTARSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTARSERVICE_EXCEPTION;
    private final static QName LISTARSERVICE_QNAME = new QName("http://ws/", "ListarService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/listar?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTARSERVICE_WSDL_LOCATION = url;
        LISTARSERVICE_EXCEPTION = e;
    }

    public ListarService() {
        super(__getWsdlLocation(), LISTARSERVICE_QNAME);
    }

    public ListarService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTARSERVICE_QNAME, features);
    }

    public ListarService(URL wsdlLocation) {
        super(wsdlLocation, LISTARSERVICE_QNAME);
    }

    public ListarService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTARSERVICE_QNAME, features);
    }

    public ListarService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListarService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Listar
     */
    @WebEndpoint(name = "ListarPort")
    public Listar getListarPort() {
        return super.getPort(new QName("http://ws/", "ListarPort"), Listar.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Listar
     */
    @WebEndpoint(name = "ListarPort")
    public Listar getListarPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "ListarPort"), Listar.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTARSERVICE_EXCEPTION!= null) {
            throw LISTARSERVICE_EXCEPTION;
        }
        return LISTARSERVICE_WSDL_LOCATION;
    }

}
