
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MeuServicoService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8081/soap?wsdl")
public class MeuServicoService
    extends Service
{

    private final static URL MEUSERVICOSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEUSERVICOSERVICE_EXCEPTION;
    private final static QName MEUSERVICOSERVICE_QNAME = new QName("http://ws/", "MeuServicoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEUSERVICOSERVICE_WSDL_LOCATION = url;
        MEUSERVICOSERVICE_EXCEPTION = e;
    }

    public MeuServicoService() {
        super(__getWsdlLocation(), MEUSERVICOSERVICE_QNAME);
    }

    public MeuServicoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEUSERVICOSERVICE_QNAME, features);
    }

    public MeuServicoService(URL wsdlLocation) {
        super(wsdlLocation, MEUSERVICOSERVICE_QNAME);
    }

    public MeuServicoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEUSERVICOSERVICE_QNAME, features);
    }

    public MeuServicoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MeuServicoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MeuServico
     */
    @WebEndpoint(name = "MeuServicoPort")
    public MeuServico getMeuServicoPort() {
        return super.getPort(new QName("http://ws/", "MeuServicoPort"), MeuServico.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeuServico
     */
    @WebEndpoint(name = "MeuServicoPort")
    public MeuServico getMeuServicoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "MeuServicoPort"), MeuServico.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEUSERVICOSERVICE_EXCEPTION!= null) {
            throw MEUSERVICOSERVICE_EXCEPTION;
        }
        return MEUSERVICOSERVICE_WSDL_LOCATION;
    }

}
